spring:
  application:
    name: chat-api
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: https://config.hustleaddiction.com/config
      username: ${CONFIG_SERVER_USERNAME}
      password: ${CONFIG_SERVER_PASSWORD}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
