spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat_api_dev?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
  application:
    name: chat-api
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: https://config.hustleaddiction.com/config
      username: ${CONFIG_SERVER_USERNAME}
      password: ${CONFIG_SERVER_PASSWORD}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
